# Generación de descripciones para imágenes con métodos XAI

Este notebook recorre la carpeta `imagenes/`, identifica las imágenes originales y las salidas XAI en subcarpetas, genera una descripción textual por imagen/método y guarda los resultados en `generacion_descripcion_XAI/resultados_descripciones_xai/`.

El flujo está pensado para las subcarpetas actuales del proyecto: `original`, `output_gradcam`, `output_lime`, `output_ig`, `output_saliency` y `output_anchor`.

## 0. Instalación opcional

Si falta alguna dependencia, ejecuta la celda siguiente. Para generar descripciones semánticas de las imágenes se usa Ollama con un modelo de visión local.

In [34]:
# Descomenta si necesitas instalar dependencias en el entorno del notebook.
# %pip install -q pandas tqdm openpyxl ollama

## 1. Imports y configuración

In [35]:
from pathlib import Path
import warnings

import pandas as pd
from tqdm.auto import tqdm
from IPython.display import display, Markdown

warnings.filterwarnings("ignore")

PROJECT_DIR = Path.cwd()
if not (PROJECT_DIR / "Imagenes").exists() and (PROJECT_DIR.parent / "Imagenes").exists():
    PROJECT_DIR = PROJECT_DIR.parent

BASE_DIR = PROJECT_DIR / "Imagenes"
OUT_DIR = PROJECT_DIR / "generacion_descripcion_XAI" / "resultados_descripciones_xai"
OUT_DIR.mkdir(parents=True, exist_ok=True)

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tif", ".tiff"}

METHOD_FOLDERS = {
    "original": "original",
    "gradcam": "output_gradcam",
    "lime": "output_lime",
    "integrated_gradients": "output_ig",
    "saliency": "output_saliency",
    "anchor": "output_anchor",
}

assert BASE_DIR.exists(), f"No existe la carpeta esperada: {BASE_DIR.resolve()}"

## 2. Cargar rutas de imágenes y asociarlas por caso

La función de normalización usa los nombres de las imágenes originales como referencia.

In [36]:
def list_images(folder: Path):
    if not folder.exists():
        return []
    return sorted(p for p in folder.iterdir() if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS)


def strip_method_suffix(stem: str) -> str:
    suffixes = [
        "_gradcam",
        "_lime",
        "_ig",
        "_saliency",
        "_anchor",
        "_comparativa_vertical",
        "_comparativa",
    ]
    for suffix in suffixes:
        if stem.endswith(suffix):
            return stem[: -len(suffix)]
    return stem


original_paths = list_images(BASE_DIR / METHOD_FOLDERS["original"])
original_stems = sorted([p.stem for p in original_paths], key=len, reverse=True)


def infer_case_id(path: Path) -> str:
    clean_stem = strip_method_suffix(path.stem)
    for original_stem in original_stems:
        if original_stem == clean_stem or original_stem in clean_stem:
            return original_stem
    return clean_stem


records = []
for method, folder_name in METHOD_FOLDERS.items():
    folder = BASE_DIR / folder_name
    for path in list_images(folder):
        records.append(
            {
                "case_id": infer_case_id(path),
                "method": method,
                "folder": folder_name,
                "image_path": str(path),
                "file_name": path.name,
            }
        )

df_images = pd.DataFrame(records).sort_values(["case_id", "method"]).reset_index(drop=True)
display(df_images.head(20))
print(f"Imágenes encontradas: {len(df_images)}")
print(f"Casos detectados: {df_images['case_id'].nunique()}")
display(pd.crosstab(df_images["case_id"], df_images["method"]).head())

,case_id,method,folder,image_path,file_name
0,image01,anchor,output_anchor,/Users/haojie/PycharmProjects/TFM-Personalized...,image01_anchor.png
1,image01,gradcam,output_gradcam,/Users/haojie/PycharmProjects/TFM-Personalized...,image01_gradcam.png
2,image01,integrated_gradients,output_ig,/Users/haojie/PycharmProjects/TFM-Personalized...,image01_ig.png
3,image01,lime,output_lime,/Users/haojie/PycharmProjects/TFM-Personalized...,image01_lime.png
4,image01,original,original,/Users/haojie/PycharmProjects/TFM-Personalized...,image01.jpg
5,image01,saliency,output_saliency,/Users/haojie/PycharmProjects/TFM-Personalized...,image01_saliency.png
6,image02,anchor,output_anchor,/Users/haojie/PycharmProjects/TFM-Personalized...,image02_anchor.png
7,image02,gradcam,output_gradcam,/Users/haojie/PycharmProjects/TFM-Personalized...,image02_gradcam.png
8,image02,integrated_gradients,output_ig,/Users/haojie/PycharmProjects/TFM-Personalized...,image02_ig.png
9,image02,lime,output_lime,/Users/haojie/PycharmProjects/TFM-Personalized...,image02_lime.png
10,image02,original,original,/Users/haojie/PycharmProjects/TFM-Personalized...,image02.jpg
11,image02,saliency,output_saliency,/Users/haojie/PycharmProjects/TFM-Personalized...,image02_saliency.png
12,image03,anchor,output_anchor,/Users/haojie/PycharmProjects/TFM-Personalized...,image03_anchor.png
13,image03,gradcam,output_gradcam,/Users/haojie/PycharmProjects/TFM-Personalized...,image03_gradcam.png
14,image03,integrated_gradients,output_ig,/Users/haojie/PycharmProjects/TFM-Personalized...,image03_ig.png
15,image03,lime,output_lime,/Users/haojie/PycharmProjects/TFM-Personalized...,image03_lime.png
16,image03,original,original,/Users/haojie/PycharmProjects/TFM-Personalized...,image03.jpg
17,image03,saliency,output_saliency,/Users/haojie/PycharmProjects/TFM-Personalized...,image03_saliency.png
18,image04,anchor,output_anchor,/Users/haojie/PycharmProjects/TFM-Personalized...,image04_anchor.png
19,image04,gradcam,output_gradcam,/Users/haojie/PycharmProjects/TFM-Personalized...,image04_gradcam.png

Imágenes encontradas: 66
Casos detectados: 11

method   anchor  gradcam  integrated_gradients  lime  original  saliency
case_id
image01       1        1                     1     1         1         1
image02       1        1                     1     1         1         1
image03       1        1                     1     1         1         1
image04       1        1                     1     1         1         1
image05       1        1                     1     1         1         1

## 3. Configurar modelo local para describir imágenes

Ollama con `qwen2.5vl:32b`

Antes de ejecutar esta sección, comprueba que Ollama esté arrancado y que el modelo exista con `ollama show qwen2.5vl:32b`. Las descripciones se generan en inglés para mantener una salida homogénea en los textos usados posteriormente.

In [37]:
USE_OLLAMA = True
OLLAMA_MODEL = "qwen2.5vl:32b"

# Importante: este modelo declara un contexto máximo enorme (262144).
# Para describir imágenes cortas no hace falta y puede hacer que la primera llamada tarde muchísimo.
OLLAMA_OPTIONS = {
    "temperature": 0.0,
    "top_p": 0.85,
    "num_ctx": 2048,
    "num_predict": 320,
}

OLLAMA_PYTHON_AVAILABLE = False
if USE_OLLAMA:
    try:
        import ollama  # noqa: F401
        OLLAMA_PYTHON_AVAILABLE = True
    except Exception as exc:
        print(
            "No se encontró el paquete Python 'ollama'. "
            "Instalalo con: pip install ollama (o uv add ollama)."
        )
        print(f"Detalle: {type(exc).__name__}: {str(exc)[:200]}")
        USE_OLLAMA = False

if not USE_OLLAMA:
    raise RuntimeError(
        "No hay backend para captions: Ollama está desactivado o no está disponible. "
        "Instala/configura Ollama y el paquete Python 'ollama'."
    )

REQUIRE_ENGLISH_CAPTIONS = True


def looks_spanish_text(text: str) -> bool:
    lowered = f" {(text or '').lower()} "
    spanish_markers = [
        " la imagen ", " el modelo ", " una visualizacion ", " una visualización ",
        " en espanol", " en español", " zonas resaltadas", " clase predicha",
        " deteccion ", " detección ", " aprendizaje ", " tortuga ", " rinc ",
    ]
    return any(marker in lowered for marker in spanish_markers)


def looks_degenerate_text(text: str) -> bool:
    t = (text or "").replace("\u00ad", "").strip()
    if not t:
        return True
    if len(t) < 25:
        return True
    lowered = t.lower()
    if REQUIRE_ENGLISH_CAPTIONS and looks_spanish_text(t):
        return True
    bad_fragments = [
        "[img-0]", "de la com", "de neu", "deep de neu", "1.1.1.1.1", "[  ]",
        "­­­­", " la tort", "\" \" \"", "“ “ “", "… …",
    ]
    if any(f in lowered for f in bad_fragments):
        return True
    compact = " ".join(lowered.split())
    if compact:
        # Detecta bucles de una palabra y repeticiones de n-gramas cortos.
        words = compact.split()
        for n, threshold in ((1, 6), (2, 5), (3, 4), (4, 4), (5, 4)):
            if len(words) >= n * threshold:
                chunks = [" ".join(words[i:i+n]) for i in range(len(words)-n+1)]
                top = max(chunks.count(ch) for ch in set(chunks))
                if top >= threshold:
                    return True
    quote_count = sum(t.count(ch) for ch in ['"', "'", "“", "”"])
    if quote_count >= 8:
        return True
    return False


def looks_incomplete_text(text: str) -> bool:
    t = clean_caption_text(text)
    if not t:
        return True
    lowered = t.lower().strip()
    incomplete_fragments = [
        "[incomplete response]", "[...]", "…", " etc", " such as the ,",
        " the and ", " and .", " or .", " is .", " are .", " most .", " more or .",
        "to represent the", "with a super-", "with a split-", "corresponding sali",
        "with sali", "is a sali", "areas of sali", "road-",
    ]
    if any(fragment in lowered for fragment in incomplete_fragments):
        return True
    if lowered.endswith(("-", ",", ":", ";", " and", " or", " the", " a", " an", " of", " with", " to", " for", " in", " by", " sali", " super", " split")):
        return True
    if t[-1] not in ".!?":
        return True
    words = lowered.rstrip(".!?").split()
    if words and words[-1] in {"the", "a", "an", "of", "with", "to", "for", "in", "by", "and", "or", "sali", "super", "split"}:
        return True
    return False


def is_valid_caption(text: str) -> bool:
    return not looks_degenerate_text(text) and not looks_incomplete_text(text)


def clean_caption_text(text: str) -> str:
    t = (text or "").replace("\u00ad", "").replace("\n", " ").strip()
    t = " ".join(t.split())
    if len(t) > 700:
        t = t[:700].rsplit(" ", 1)[0].rstrip(",;:-") + "."
    return t


def build_prompt_for_method(method: str) -> str:
    if method == "original":
        return (
            "Describe the original image in English in one complete sentence of 20 to 45 words. "
            "Mention only visible objects or scene elements. Do not invent information. "
            "Do not use lists or markdown. End with a complete sentence."
        )
    if method == "comparativa":
        return (
            "This is a composite comparison panel with an original image and several XAI views. "
            "Describe in English, in one complete sentence of 25 to 60 words, which panels or highlighted regions stand out and whether the explanations look consistent. "
            "Do not list every panel. Do not use markdown. End with a complete sentence."
        )
    return (
        "Describe this XAI visualization in English in one complete sentence of 25 to 55 words. "
        "Mention the visible highlighted areas (warm, bright, masked, or marked regions) and the general interpretation they suggest. "
        "Do not identify uncertain brands or unclear text. Do not use lists or markdown. End with a complete sentence."
    )


def ollama_caption_attempt(path: str, prompt: str, attempt_instruction: str, num_predict: int = 420) -> str:
    import ollama

    response = ollama.chat(
        model=OLLAMA_MODEL,
        messages=[
            {
                "role": "system",
                "content": "You write concise, complete image captions only in English. Never answer in Spanish. Never repeat words or phrases. Always finish the final sentence.",
            },
            {
                "role": "user",
                "content": prompt + " " + attempt_instruction,
                "images": [str(Path(path).resolve())],
            },
        ],
        think=False,
        options={**OLLAMA_OPTIONS, "num_predict": num_predict, "temperature": 0.0, "top_p": 0.8},
        keep_alive="5m",
    )
    return clean_caption_text(response["message"]["content"])


def caption_image(path: str, method: str = "original") -> str:
    prompt = build_prompt_for_method(method)
    attempt_instructions = [
        "Return only the final caption.",
        "Try again with a shorter complete caption of 20 to 40 words. Return only the caption.",
        "Describe only the visible colors, masks, heatmaps, and highlighted regions. Return one complete sentence.",
        "If the image is complex, give a generic but image-specific XAI caption based only on visible regions. Return one complete sentence.",
    ]
    try:
        for attempt_idx, instruction in enumerate(attempt_instructions, start=1):
            caption = ollama_caption_attempt(path, prompt, instruction, num_predict=420)
            if is_valid_caption(caption):
                return caption
            print(f"Caption rejected attempt {attempt_idx}/{len(attempt_instructions)} for {Path(path).name}: {caption[:180]}", flush=True)
    except Exception as exc:
        print(f"Ollama fallo con {path}: {type(exc).__name__}: {str(exc)[:200]}")
    return ""

### Comprobación de Ollama y GPU/Metal

En Mac Apple Silicon, Ollama usa Metal/GPU automáticamente cuando el modelo y la memoria lo permiten. Esta celda comprueba que el modelo existe y recuerda cómo verificar el uso real de GPU durante una inferencia.

In [38]:
import subprocess


def run_ollama_command(args):
    try:
        result = subprocess.run(args, capture_output=True, text=True, check=False)
        return result.returncode, result.stdout.strip(), result.stderr.strip()
    except FileNotFoundError:
        return 127, "", "No se encontró el comando 'ollama'. Instala Ollama o abre Jupyter desde una terminal donde esté disponible."


code, stdout, stderr = run_ollama_command(["ollama", "show", OLLAMA_MODEL])
if code == 0:
    print(f"Modelo Ollama encontrado: {OLLAMA_MODEL}")
    capability_lines = [line for line in stdout.splitlines() if "vision" in line.lower() or "requires" in line.lower()]
    if capability_lines:
        print("\n".join(capability_lines))
else:
    print(f"No se pudo comprobar el modelo {OLLAMA_MODEL}.")
    print(stderr or stdout)

print("\nDurante la ejecución de captions, abre otra terminal y usa: ollama ps")
print("Opciones Ollama usadas:", OLLAMA_OPTIONS)

Modelo Ollama encontrado: qwen2.5vl:32b
    vision

Durante la ejecución de captions, abre otra terminal y usa: ollama ps
Opciones Ollama usadas: {'temperature': 0.0, 'top_p': 0.85, 'num_ctx': 2048, 'num_predict': 320}

### Prueba rápida con una sola imagen

Activa esta celda antes del lote completo si quieres validar una imagen aislada. Si tarda varios minutos, el problema está en el modelo/configuración y no en el bucle.

In [39]:
import time

TEST_SINGLE_IMAGE = False

if TEST_SINGLE_IMAGE:
    test_row = df_images[df_images["method"] == "original"].iloc[0]
    print("Imagen de prueba:", test_row["image_path"])
    start = time.perf_counter()
    test_caption = caption_image(test_row["image_path"], method="original")
    elapsed = time.perf_counter() - start
    print(f"Tiempo: {elapsed:.1f}s")
    print(test_caption)

## 4. Leer metadatos de Anchor y utilidades de descripción

In [40]:
def parse_anchor_metadata(case_id: str):
    folder = BASE_DIR / METHOD_FOLDERS["anchor"]
    if not folder.exists():
        return {}
    candidates = [p for p in folder.glob("*.txt") if case_id in p.stem]
    if not candidates:
        return {}

    metadata = {"anchor_txt_path": str(candidates[0])}
    text = candidates[0].read_text(encoding="utf-8", errors="ignore")
    for line in text.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        metadata[key.strip()] = value.strip()
    return metadata


def format_prob(value):
    try:
        return f"{float(value):.3f}"
    except Exception:
        return value


METHOD_EXPLANATIONS = {
    "original": "Original image used as the reference for comparing the XAI explanations.",
    "gradcam": "Grad-CAM highlights the warm regions of the map as the most relevant areas, indicating the parts of the image that most influenced the predicted class.",
    "lime": "LIME divides the image into superpixels and marks the regions that most support the model prediction.",
    "integrated_gradients": "Integrated Gradients assigns importance to pixels by comparing the image with a baseline reference; the most intense regions concentrate the strongest contribution to the prediction.",
    "saliency": "Saliency Maps highlight the pixels where small changes would most affect the model output; brighter areas indicate greater sensitivity.",
    "anchor": "Anchor Image identifies a set of superpixels that act as a sufficient rule for preserving the model prediction.",
    "comparativa": "Comparative image that groups the original image and several XAI explanations to review the consistency of the methods together.",
}


METHOD_FALLBACK_CAPTIONS = {
    "gradcam": "The Grad-CAM output should be interpreted as a heatmap where warmer regions indicate the image areas that contributed most strongly to the predicted class.",
    "lime": "The LIME output should be interpreted as a superpixel-based explanation where the marked regions indicate the image segments that most support the model prediction.",
    "integrated_gradients": "The Integrated Gradients output should be interpreted as an attribution map where the most intense regions indicate pixels with the strongest contribution relative to a baseline image.",
    "saliency": "The Saliency Map output should be interpreted as a sensitivity map where brighter regions indicate pixels whose small changes would most affect the model output.",
    "anchor": "The Anchor Image output should be interpreted as a masked superpixel explanation where the visible selected regions form a sufficient visual rule for preserving the prediction.",
    "comparativa": "The comparative XAI output should be interpreted as a side-by-side summary that allows the original image and multiple explanation methods to be checked for consistency.",
}


def build_fallback_xai_caption(row, original_caption_by_case, anchor_meta_by_case):
    method = row["method"]
    if method == "original":
        return ""

    fallback = METHOD_FALLBACK_CAPTIONS.get(method, "This XAI output should be interpreted as a visual explanation of the regions used by the model for its prediction.")
    base_caption = original_caption_by_case.get(row["case_id"], "")
    if base_caption:
        fallback += f" The explanation belongs to a base image described as: {base_caption}."

    if method == "anchor":
        meta = anchor_meta_by_case.get(row["case_id"], {})
        anchor_bits = []
        if meta.get("pred_class_name"):
            anchor_bits.append(f"predicted class '{meta['pred_class_name']}'")
        if meta.get("precision"):
            anchor_bits.append(f"precision {format_prob(meta['precision'])}")
        if meta.get("coverage"):
            anchor_bits.append(f"coverage {format_prob(meta['coverage'])}")
        if meta.get("anchor_features (superpixels)"):
            anchor_bits.append(f"anchor superpixels {meta['anchor_features (superpixels)']}")
        if anchor_bits:
            fallback += " Anchor metadata: " + ", ".join(anchor_bits) + "."

    return clean_caption_text(fallback)


def build_xai_description(row, original_caption_by_case, xai_caption_by_path, anchor_meta_by_case):
    method = row["method"]
    case_id = row["case_id"]
    base_caption = original_caption_by_case.get(case_id, "")
    xai_caption = xai_caption_by_path.get(row["image_path"], "")
    if method != "original" and not str(xai_caption).strip():
        xai_caption = build_fallback_xai_caption(row, original_caption_by_case, anchor_meta_by_case)
    method_text = METHOD_EXPLANATIONS.get(method, "XAI output associated with the image.")

    pieces = []
    if base_caption:
        pieces.append(f"The base image shows: {base_caption}.")
    if method == "original":
        pieces.append(method_text)
    else:
        pieces.append(f"Method {method}: {method_text}")
    if method != "original" and xai_caption and xai_caption != base_caption:
        pieces.append(f"The generated visualization can be visually described as: {xai_caption}.")

    if method == "anchor":
        meta = anchor_meta_by_case.get(case_id, {})
        pred_name = meta.get("pred_class_name")
        pred_prob = meta.get("pred_prob")
        precision = meta.get("precision")
        coverage = meta.get("coverage")
        features = meta.get("anchor_features (superpixels)")
        anchor_details = []
        if pred_name:
            anchor_details.append(f"predicted class '{pred_name}'")
        if pred_prob:
            anchor_details.append(f"probability {format_prob(pred_prob)}")
        if precision:
            anchor_details.append(f"precision {format_prob(precision)}")
        if coverage:
            anchor_details.append(f"coverage {format_prob(coverage)}")
        if features:
            anchor_details.append(f"anchor superpixels {features}")
        if anchor_details:
            pieces.append("Anchor metadata: " + ", ".join(anchor_details) + ".")

    return " ".join(pieces).strip()


anchor_meta_by_case = {case_id: parse_anchor_metadata(case_id) for case_id in df_images["case_id"].unique()}

## 5. Generar captions y descripciones

Esta sección se detiene si detecta que varias imágenes originales reciben exactamente la misma descripción, porque eso suele indicar que el modelo de visión no está leyendo las imágenes.

In [41]:
import time

SHOW_IMAGE_PROGRESS = True
CAPTION_PROGRESS_PREVIEW_CHARS = 700
APPLY_FALLBACK_CAPTIONS = False


def caption_rows_with_progress(rows: pd.DataFrame, desc: str):
    captions = {}
    total = len(rows)
    iterator = tqdm(rows.reset_index(drop=True).iterrows(), total=total, desc=desc)
    for idx, (_, row) in enumerate(iterator, start=1):
        image_path = row["image_path"]
        method = row["method"]
        case_id = row["case_id"]
        iterator.set_postfix_str(f"{idx}/{total} {method} {Path(image_path).name[:35]}")

        if SHOW_IMAGE_PROGRESS:
            print(f"[{idx}/{total}] Procesando {method} | caso={case_id} | archivo={Path(image_path).name}", flush=True)

        start = time.perf_counter()
        caption = caption_image(image_path, method=method)
        elapsed = time.perf_counter() - start

        if SHOW_IMAGE_PROGRESS:
            preview = caption.replace("\n", " ")[:CAPTION_PROGRESS_PREVIEW_CHARS]
            status = "OK" if caption else "REJECTED/EMPTY"
            print(f"[{idx}/{total}] Terminado en {elapsed:.1f}s | {status} | {preview}", flush=True)

        caption = clean_caption_text(caption)
        captions[image_path] = caption
    return captions


original_rows = df_images[df_images["method"] == "original"]
original_caption_by_path = caption_rows_with_progress(original_rows, "Captions originales")
original_caption_by_case = dict(zip(original_rows["case_id"], original_rows["image_path"].map(original_caption_by_path)))

unique_original_captions = {caption for caption in original_caption_by_case.values() if str(caption).strip()}
if len(original_caption_by_case) > 1 and len(unique_original_captions) <= 1:
    raise RuntimeError(
        "Todas las imágenes originales han recibido el mismo caption. "
        "Esto indica que el modelo de visión no está interpretando las imágenes correctamente; "
        "detén la ejecución, revisa Ollama/modelo y regenera los resultados."
    )


# Con Ollama vision conviene describir tambien cada salida XAI.
# Si va demasiado lento con el modelo de visión local, cambia a False.
CAPTION_XAI_OUTPUTS = True
xai_caption_by_path = {}

if CAPTION_XAI_OUTPUTS:
    xai_rows = df_images[df_images["method"] != "original"]
    xai_caption_by_path = caption_rows_with_progress(xai_rows, "Captions XAI")

xai_caption_series = pd.Series(xai_caption_by_path, dtype="object")
xai_caption_ok = xai_caption_series.fillna("").astype(str).str.strip().ne("")
coverage_ratio = xai_caption_ok.mean() if len(xai_caption_ok) else 1.0

if CAPTION_XAI_OUTPUTS and coverage_ratio < 0.8:
    missing_xai_paths = xai_caption_series.index[~xai_caption_ok].tolist()
    missing_xai_rows = df_images[df_images["image_path"].isin(missing_xai_paths)]
    print(
        f"Warning: low XAI caption coverage ({coverage_ratio:.1%}). "
        "The notebook will continue using the method explanation as a fallback for those rows."
    )
    if not missing_xai_rows.empty:
        display(missing_xai_rows[["case_id", "method", "file_name"]].sort_values(["method", "case_id"]))

if APPLY_FALLBACK_CAPTIONS:
    for _, row in df_images[df_images["method"] != "original"].iterrows():
        image_path = row["image_path"]
        if not str(xai_caption_by_path.get(image_path, "")).strip():
            xai_caption_by_path[image_path] = build_fallback_xai_caption(row, original_caption_by_case, anchor_meta_by_case)
    print(f"Fallback XAI captions applied where needed. Non-empty XAI captions: {sum(bool(str(v).strip()) for v in xai_caption_by_path.values())}/{len(xai_caption_by_path)}")
else:
    print(f"Fallback disabled. Model-generated non-empty XAI captions: {sum(bool(str(v).strip()) for v in xai_caption_by_path.values())}/{len(xai_caption_by_path)}")
    pending_model_caption_paths = [path for path, caption in xai_caption_by_path.items() if not str(caption).strip()]
    pending_model_caption_rows = df_images[df_images["image_path"].isin(pending_model_caption_paths)]
    if not pending_model_caption_rows.empty:
        display(pending_model_caption_rows[["case_id", "method", "file_name", "image_path"]].sort_values(["method", "case_id"]))

df_descriptions = df_images.copy()
df_descriptions["caption_original"] = df_descriptions["case_id"].map(original_caption_by_case)
df_descriptions["caption_xai"] = df_descriptions["image_path"].map(xai_caption_by_path).fillna("")
df_descriptions["descripcion"] = df_descriptions.apply(
    lambda row: build_xai_description(row, original_caption_by_case, xai_caption_by_path, anchor_meta_by_case),
    axis=1,
)

display(df_descriptions[["case_id", "method", "image_path", "descripcion"]].head(20))

Captions originales:   0%|          | 0/11 [00:00<?, ?it/s]

[1/11] Procesando original | caso=image01 | archivo=image01.jpg

[1/11] Terminado en 20.5s | OK | A bird of prey, with dark brown and white plumage, soars gracefully through a clear blue sky, its wings fully extended and tail feathers fanned out as it glides forward.
[2/11] Procesando original | caso=image02 | archivo=image02.jpg
[2/11] Terminado en 14.1s | OK | A close-up profile of a duck showcases its vibrant green head, contrasting black and brown feathers, and a bright yellow beak, set against a plain white background.
[3/11] Procesando original | caso=image03 | archivo=image03.jpg
[3/11] Terminado en 13.7s | OK | A snake with a dark, glossy body and a lighter underside coils gracefully on a rough, light-colored gravel surface, casting a subtle shadow.
[4/11] Procesando original | caso=image04 | archivo=image04.jpg
[4/11] Terminado en 19.1s | OK | A small spider with a dark, glossy body and slender legs is perched on a green leaf with white speckles, set against a neutral background with a scale bar in the top left corner.
[5/11] Procesando original | caso=image05 | archivo=image05.jpg
[5/11] Terminado en 14.1s | OK | A vibrant blue butterfly rests on a leafy plant, its wings shimmering in contrast to the grayscale background, surrounded by various foliage and delicate white flowers.
[6/11] Procesando original | caso=image06 | archivo=image06.jpg
[6/11] Terminado en 13.9s | OK | A majestic white tiger with distinct black stripes stands alert on a rocky surface, surrounded by lush green foliage and trees in a naturalistic setting.
[7/11] Procesando original | caso=image07 | archivo=image07.jpg
[7/11] Terminado en 14.1s | OK | A black-and-white bird with a slender neck and long legs stands in shallow water, its reflection mirrored on the calm surface, creating a serene and symmetrical scene.
[8/11] Procesando original | caso=image08 | archivo=image08.jpg
[8/11] Terminado en 12.5s | OK | A butterfly with black wings adorned with orange and white spots rests on a white wooden structure, surrounded by tall green leaves and a blurred green background.
[9/11] Procesando original | caso=image09 | archivo=image09.jpg
Caption rejected attempt 1/4 for image09.jpg: A man in a red SPD shirt holds a hawk perched on a leather glove, smiling as he interacts with a crowd of people at an outdoor event near a red booth with hanging white birds.
Caption rejected attempt 2/4 for image09.jpg: A man in a red SPD shirt holds a hawk on a gloved hand, smiling as he interacts with a crowd at an outdoor event, with a backdrop featuring a red banner and hanging white birds. A
Caption rejected attempt 3/4 for image09.jpg: A man in a red SPD shirt smiles while holding a large bird of prey on a gloved hand, surrounded by people in a grassy outdoor setting with a red backdrop featuring the SPD logo and
Caption rejected attempt 4/4 for image09.jpg: A man in a red SPD shirt holds a falcon on a gloved hand, smiling as he interacts with a crowd at an outdoor event, with a backdrop featuring a red banner and a wooden structure.
[9/11] Terminado en 30.8s | REJECTED/EMPTY |
[10/11] Procesando original | caso=image10 | archivo=image10.jpg
[10/11] Terminado en 14.4s | OK | A young elephant stands amidst tall grass, its large ears spread wide, and its trunk hanging down, showcasing its textured gray skin and small tusks in a natural, grassy environment.
[11/11] Procesando original | caso=image11 | archivo=image11.jpg
[11/11] Terminado en 15.1s | OK | A turtle with a patterned shell rests on a weathered tree stump protruding from calm, murky water, surrounded by scattered green algae.

Captions XAI:   0%|          | 0/55 [00:00<?, ?it/s]

[1/55] Procesando anchor | caso=image01 | archivo=image01_anchor.png
[1/55] Terminado en 12.4s | OK | This XAI visualization compares an original image of a bird in flight with its masked anchor representation, segmented superpixels, and an overlay indicating a kite detection with high precision but zero coverage, highlighting the model's focus on specific regions while missing the broader context.
[2/55] Procesando gradcam | caso=image01 | archivo=image01_gradcam.png
[2/55] Terminado en 11.7s | OK | This XAI visualization compares an original image of a bird in flight with a heatmap and an overlay, highlighting a warm, bright region around the bird's body and wings, suggesting that the model's attention is focused on these areas, likely indicating the bird's identification as a kite with a logit score of 6.43.
[3/55] Procesando integrated_gradients | caso=image01 | archivo=image01_ig.png
[3/55] Terminado en 13.9s | OK | This XAI visualization compares an original image of a bird in flight with its corresponding IG |abs| (gris) grayscale representation, IG heatmap, and an overlay with a kite (0.28) score, highlighting the bird's wings and body as the most influential features for model predictions, suggesting these areas are critical for accurate classification.
[4/55] Procesando lime | caso=image01 | archivo=image01_lime.png
[4/55] Terminado en 11.0s | OK | This XAI visualization compares an original image of a bird in flight with a superpixel mask and a LIME kite explanation, highlighting the bird's silhouette and key features in warm, bright, and marked regions, suggesting the model's focus on the bird's shape and edges for accurate detection.
[5/55] Procesando saliency | caso=image01 | archivo=image01_saliency.png
[5/55] Terminado en 11.6s | OK | This XAI visualization compares an original image of a bird in flight with a saliency map highlighting areas of high importance, and an overlay indicating the presence of a kite with a logit score of 6.43, suggesting the model's focus on the bird's wings and body as key features for identifying the kite.
[6/55] Procesando anchor | caso=image02 | archivo=image02_anchor.png
[6/55] Terminado en 12.6s | OK | This XAI visualization compares an original image of a duck with its masked anchor, superpixel segmentation, and an overlay indicating the model's prediction confidence, highlighting how the model focuses on the duck's head and beak, suggesting these features are critical for accurate classification.
[7/55] Procesando gradcam | caso=image02 | archivo=image02_gradcam.png
[7/55] Terminado en 11.8s | OK | This XAI visualization compares an original image of a duck with a heatmap and an overlay, highlighting the duck's head and neck area in warm, bright colors, indicating a high likelihood of the model's focus on these features to classify the image as a "drake" with a logit score of 6.39.
[8/55] Procesando integrated_gradients | caso=image02 | archivo=image02_ig.png
[8/55] Terminado en 13.7s | OK | This XAI visualization compares an original image of a duck with its Integrated Gradients (IG) absolute value grayscale representation, a blue IG heatmap, and an overlay showing the IG heatmap integrated with the original image, highlighting areas of high importance, particularly around the duck's eye and beak, suggesting these features are crucial for model interpretation.
[9/55] Procesando lime | caso=image02 | archivo=image02_lime.png
[9/55] Terminado en 11.3s | OK | This XAI visualization compares an original image of a duck's head with a superpixel mask and a LIME drake explanation, highlighting key areas in yellow that suggest the model's focus on the duck's head shape, eye, and beak, indicating these features are crucial for the model's decision-making process.
[10/55] Procesando saliency | caso=image02 | archivo=image02_saliency.png
[10/55] Terminado en 11.5s | OK | This XAI visualization compares an original image of a duck's head with a saliency map and an overlay, highlighting the duck's eye and beak as the most salient features, suggesting these areas are crucial for identifying the duck as a "drake" with a high confidence score of 6.39.
[11/55] Procesando anchor | caso=image03 | archivo=image03_anchor.png
[11/55] Terminado en 13.1s | OK | This XAI visualization compares an original image of a snake with its masked anchor, superpixel segmentation, and an overlay highlighting the snake with a precision of 1.00 and coverage of 0.51, indicating areas of focus and segmentation accuracy for the snake's detection and analysis.
[12/55] Procesando gradcam | caso=image03 | archivo=image03_gradcam.png
[12/55] Terminado en 11.9s | OK | This XAI visualization compares an original image of a snake on a sandy surface with a heatmap and an overlay, highlighting the central area of the snake with warm, bright colors, indicating a high confidence score of 6.71 for the classification as a "thunder snake," suggesting the model focuses on the snake's body for accurate identification.
[13/55] Procesando integrated_gradients | caso=image03 | archivo=image03_ig.png
[13/55] Terminado en 15.3s | OK | This XAI visualization compares an original image of a snake with its Integrated Gradients (IG) absolute value heatmap, showing a focus on the snake's body and head, particularly highlighting the textured scales and distinct patterns, which are then overlaid onto the original image to emphasize the model's attention to these features, suggesting their importance in identifying the snake as a "thunder snake" with a confidence score of 0.40.
[14/55] Procesando lime | caso=image03 | archivo=image03_lime.png
[14/55] Terminado en 12.5s | OK | This XAI visualization compares an original image of a snake with a superpixel mask and a LIME explanation, highlighting the snake's body and tail in yellow, indicating areas of high importance for the model's classification of the snake as a "thunder snake" with a confidence score of 0.40, suggesting the model focuses on the snake's shape and texture for identification.
[15/55] Procesando saliency | caso=image03 | archivo=image03_saliency.png
[15/55] Terminado en 12.1s | OK | This XAI visualization compares an original image of a snake on a sandy surface with its saliency map and an overlay indicating the presence of a "thunder snake" with a logit score of 6.71, highlighting the snake's body in warm, bright regions, suggesting the model's focus on the snake as the primary subject of interest.
[16/55] Procesando anchor | caso=image04 | archivo=image04_anchor.png
[16/55] Terminado en 13.3s | OK | This XAI visualization compares an original image of a wolf spider with its masked anchor, superpixel segmentation, and an overlay highlighting the spider with a precision of 1.00 and coverage of 0.01, indicating a focused and accurate segmentation process that isolates the spider from its background effectively.
[17/55] Procesando gradcam | caso=image04 | archivo=image04_gradcam.png
[17/55] Terminado en 11.1s | OK | This XAI visualization compares an original image of a wolf spider with a heatmap and an overlay, highlighting the spider's body and legs in warm, bright colors, indicating areas of high importance or confidence (logit=6.21), suggesting the model's focus on these features for accurate identification.
[18/55] Procesando integrated_gradients | caso=image04 | archivo=image04_ig.png
Caption rejected attempt 1/4 for image04_ig.png: This XAI visualization compares an original image of a wolf spider with its Integrated Gradients (IG) absolute value (IG |abs|) grayscale representation, a corresponding IG heatmap
Caption rejected attempt 2/4 for image04_ig.png: This XAI visualization compares an original image of a wolf spider with its Integrated Gradients (IG) absolute value (IG |abs|) grayscale representation, a blue IG heatmap, and an
[18/55] Terminado en 32.7s | OK | This XAI visualization compares an original image of a wolf spider with its IG |abs| (gris) representation, IG heatmap, and an overlay, highlighting the spider's features with warm, bright regions that suggest areas of high importance or saliency, particularly around the spider's legs and body, indicating key visual elements contributing to its identification.
[19/55] Procesando lime | caso=image04 | archivo=image04_lime.png
[19/55] Terminado en 10.9s | OK | This XAI visualization compares an original image of a wolf spider on a leaf with a superpixel mask and a LIME explanation, highlighting the spider's body and legs in yellow, indicating their importance in the model's decision-making process, suggesting these features are key for identifying the spider.
[20/55] Procesando saliency | caso=image04 | archivo=image04_saliency.png
[20/55] Terminado en 11.5s | OK | This XAI visualization compares an original image of a wolf spider on a leaf with its saliency map and an overlay, highlighting the spider's features in bright blue regions, indicating areas of high importance for the model's classification decision, suggesting the spider's distinct characteristics are key to its identification.
[21/55] Procesando anchor | caso=image05 | archivo=image05_anchor.png
[21/55] Terminado en 13.2s | OK | This XAI visualization compares an original image of a butterfly with its masked version, superpixel segmentation, and an overlay highlighting the butterfly with precision of 1.00 and coverage of 0.07, indicating a focus on the butterfly's accurate identification and minimal surrounding area inclusion.
[22/55] Procesando gradcam | caso=image05 | archivo=image05_gradcam.png
[22/55] Terminado en 11.1s | OK | This XAI visualization compares an original grayscale image of a butterfly with a heatmap and an overlay, highlighting the butterfly's presence with warm, bright regions, indicating a high confidence score (logit=4.80), suggesting the model accurately identifies the butterfly as the focal point of interest.
[23/55] Procesando integrated_gradients | caso=image05 | archivo=image05_ig.png
[23/55] Terminado en 13.9s | OK | This XAI visualization compares an original grayscale image of a butterfly on leaves with its Integrated Gradients (IG) absolute value heatmap, showing concentrated blue highlights around the butterfly and leaf edges, and an overlay indicating a bee detection confidence of 0.08, suggesting the model's focus on the butterfly's features while also identifying a low-confidence bee presence.
[24/55] Procesando lime | caso=image05 | archivo=image05_lime.png
[24/55] Terminado en 10.3s | OK | This XAI visualization compares an original image of a butterfly on leaves with a superpixel mask and a LIME bee explanation, highlighting the butterfly and its immediate surroundings in yellow, indicating the model's focus on these areas as key features for identifying the butterfly.
[25/55] Procesando saliency | caso=image05 | archivo=image05_saliency.png
[25/55] Terminado en 11.8s | OK | This XAI visualization compares an original grayscale image of a butterfly on a plant with a saliency map highlighting areas of interest in blue, and an overlay indicating the presence of a bee with a logit score of 4.80, marked by bright green spots, suggesting the model's focus on specific regions related to the bee's detection.
[26/55] Procesando anchor | caso=image06 | archivo=image06_anchor.png
[26/55] Terminado en 12.9s | OK | This XAI visualization compares an original image of a white tiger with its masked anchor representation, segmented superpixels, and an overlay highlighting the tiger with a precision of 1.00 and coverage of 0.50, indicating areas of focus and segmentation accuracy for explainable AI analysis.
[27/55] Procesando gradcam | caso=image06 | archivo=image06_gradcam.png
[27/55] Terminado en 10.6s | OK | This XAI visualization compares an original image of a white tiger with a heatmap and an overlay, highlighting the tiger's body with warm, bright colors, indicating areas of high importance or confidence in the model's classification, suggesting the tiger is the primary focus of the analysis.
[28/55] Procesando integrated_gradients | caso=image06 | archivo=image06_ig.png
[28/55] Terminado en 13.9s | OK | This XAI visualization compares an original image of a white tiger with its Integrated Gradients (IG) absolute value heatmap, showing a grayscale representation of feature importance, and an overlay highlighting the tiger's body with a score of 0.38, indicating areas of significant contribution to the model's prediction, primarily focusing on the tiger's form and texture.
[29/55] Procesando lime | caso=image06 | archivo=image06_lime.png
[29/55] Terminado en 11.0s | OK | This XAI visualization compares an original image of a white tiger with a superpixel mask and a LIME tiger explanation, highlighting the tiger's outline in yellow, indicating the model's focus on the tiger's shape and features, suggesting that these visual elements are crucial for the model's decision-making process.
[30/55] Procesando saliency | caso=image06 | archivo=image06_saliency.png
[30/55] Terminado en 11.0s | OK | This XAI visualization compares an original image of a white tiger with its saliency map and an overlay, highlighting areas of high importance for tiger detection, indicated by warm, bright spots on the tiger's body, suggesting the model focuses on distinct features like stripes and facial patterns to identify the subject.
[31/55] Procesando anchor | caso=image07 | archivo=image07_anchor.png
[31/55] Terminado en 13.4s | OK | This XAI visualization compares an original image of an American egret with its masked anchor, superpixel segmentation, and an overlay highlighting the bird's presence with warm, bright regions, indicating high precision (0.97) and moderate coverage (0.26), suggesting effective segmentation and detection of the bird in the scene.
[32/55] Procesando gradcam | caso=image07 | archivo=image07_gradcam.png
[32/55] Terminado en 10.8s | OK | This XAI visualization compares an original image of an American egret with a heatmap and an overlay, highlighting the bird's body and head in warm, bright colors, indicating areas of high importance or confidence in the model's classification, suggesting the model focuses on these regions to identify the bird.
[33/55] Procesando integrated_gradients | caso=image07 | archivo=image07_ig.png
Caption rejected attempt 1/4 for image07_ig.png: This XAI visualization compares an original image of an American egret with its IG (Integrated Gradients) absolute value grayscale representation, a blue IG heatmap, and an overlay
Caption rejected attempt 2/4 for image07_ig.png: This XAI visualization compares an original image of an American egret with its Integrated Gradients (IG) absolute value grayscale, IG heatmap, and overlay, highlighting the bird's
[33/55] Terminado en 31.3s | OK | This XAI visualization compares an original image of an American egret with its corresponding IG |abs| (gris) mask, IG heatmap, and an overlay, highlighting the bird's features with warm, bright regions that suggest the model's focus on the egret's head, neck, and body, indicating these areas as significant for identification.
[34/55] Procesando lime | caso=image07 | archivo=image07_lime.png
[34/55] Terminado en 10.8s | OK | This XAI visualization compares an original image of an American egret with a superpixel mask and a LIME explanation, highlighting the bird's body and head in yellow, indicating areas of high importance for the model's classification decision, suggesting that these features are critical for identifying the egret.
[35/55] Procesando saliency | caso=image07 | archivo=image07_saliency.png
[35/55] Terminado en 11.1s | OK | This XAI visualization compares an original image of an American egret with its saliency map and an overlay, highlighting the bird's features with warm, bright regions, indicating areas of high importance for the model's classification decision, suggesting the egret's distinct shape and coloration are key factors in its identification.
[36/55] Procesando anchor | caso=image08 | archivo=image08_anchor.png
[36/55] Terminado en 13.4s | OK | This XAI visualization compares an original image of a butterfly on a leaf with its masked anchor representation, superpixel segmentation, and an overlay highlighting the butterfly with a precision of 1.00 and coverage of 0.52, indicating the model's focus on the butterfly while also capturing surrounding areas.
[37/55] Procesando gradcam | caso=image08 | archivo=image08_gradcam.png
[37/55] Terminado en 12.5s | OK | This XAI visualization compares an original image of a butterfly on a plant with a heatmap and an overlay, highlighting the butterfly's features in warm, bright colors, indicating the model's focus on the butterfly's pattern and shape, suggesting the butterfly is the primary subject of interest with a high confidence score of 6.40.
[38/55] Procesando integrated_gradients | caso=image08 | archivo=image08_ig.png
[38/55] Terminado en 14.4s | OK | This XAI visualization compares an original image of a butterfly on a leaf with its corresponding IG |abs| (gris) grayscale representation, IG heatmap, and an overlay highlighting the butterfly as an "admiral" with a confidence score of 0.31, indicating the model's focus on the butterfly's features as key for its classification.
[39/55] Procesando lime | caso=image08 | archivo=image08_lime.png
[39/55] Terminado en 13.0s | OK | This XAI visualization compares an original image of a butterfly on grass with a superpixel mask and a LIME (Local Interpretable Model-agnostic Explanations) heatmap, highlighting the butterfly's outline in yellow, indicating its significant contribution to the model's classification as a "LIME admiral" with a score of 0.31, suggesting the butterfly's features are crucial for the model's decision.
[40/55] Procesando saliency | caso=image08 | archivo=image08_saliency.png
[40/55] Terminado en 11.7s | OK | This XAI visualization compares an original image of a butterfly on grass with a saliency map highlighting areas of high importance in blue, and an overlay indicating the butterfly as an "admiral" with a logit score of 6.40, suggesting the model's focus on the butterfly's distinct features for accurate classification.
[41/55] Procesando anchor | caso=image09 | archivo=image09_anchor.png
[41/55] Terminado en 12.4s | OK | This XAI visualization compares an original image with an anchor-based masked version, superpixel segmentation, and an overlay chain mail explanation, highlighting the bird and the person's arm as key features, suggesting these elements are crucial for the model's decision-making process.
[42/55] Procesando gradcam | caso=image09 | archivo=image09_gradcam.png
[42/55] Terminado en 11.1s | OK | This XAI visualization compares an original image of a man holding a bird with a heatmap and an overlay, highlighting the bird as the primary focus with warm, bright regions, suggesting the model's attention is concentrated on the bird, as indicated by the logit value of 3.37.
[43/55] Procesando integrated_gradients | caso=image09 | archivo=image09_ig.png
[43/55] Terminado en 15.1s | OK | This XAI visualization compares an original image of a person holding a bird with a red shirt and a glove, alongside an IG |abs| (gris) grayscale image highlighting areas of importance, an IG heatmap emphasizing the bird and glove with bright blue regions, and an overlay chain mail visualization with a 0.02 threshold, indicating the bird and glove as key features contributing to the model's decision-making process.
[44/55] Procesando lime | caso=image09 | archivo=image09_lime.png
[44/55] Terminado en 10.5s | OK | This XAI visualization compares an original image of a man holding a bird with a superpixel mask and a LIME chain mail explanation, highlighting the bird and the man's arm as key features, suggesting these elements are significant in the model's decision-making process.
[45/55] Procesando saliency | caso=image09 | archivo=image09_saliency.png

,case_id,method,image_path,descripcion
0,image01,anchor,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A bird of prey, with dar..."
1,image01,gradcam,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A bird of prey, with dar..."
2,image01,integrated_gradients,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A bird of prey, with dar..."
3,image01,lime,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A bird of prey, with dar..."
4,image01,original,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A bird of prey, with dar..."
5,image01,saliency,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A bird of prey, with dar..."
6,image02,anchor,/Users/haojie/PycharmProjects/TFM-Personalized...,The base image shows: A close-up profile of a ...
7,image02,gradcam,/Users/haojie/PycharmProjects/TFM-Personalized...,The base image shows: A close-up profile of a ...
8,image02,integrated_gradients,/Users/haojie/PycharmProjects/TFM-Personalized...,The base image shows: A close-up profile of a ...
9,image02,lime,/Users/haojie/PycharmProjects/TFM-Personalized...,The base image shows: A close-up profile of a ...
10,image02,original,/Users/haojie/PycharmProjects/TFM-Personalized...,The base image shows: A close-up profile of a ...
11,image02,saliency,/Users/haojie/PycharmProjects/TFM-Personalized...,The base image shows: A close-up profile of a ...
12,image03,anchor,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A snake with a dark, glo..."
13,image03,gradcam,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A snake with a dark, glo..."
14,image03,integrated_gradients,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A snake with a dark, glo..."
15,image03,lime,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A snake with a dark, glo..."
16,image03,original,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A snake with a dark, glo..."
17,image03,saliency,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A snake with a dark, glo..."
18,image04,anchor,/Users/haojie/PycharmProjects/TFM-Personalized...,The base image shows: A small spider with a da...
19,image04,gradcam,/Users/haojie/PycharmProjects/TFM-Personalized...,The base image shows: A small spider with a da...

## 6. Crear resumen por caso

Además de una fila por imagen/método, se crea un texto compacto por caso con todas las explicaciones disponibles.

In [42]:
def build_case_summary(group: pd.DataFrame) -> str:
    case_id = group.name
    caption = group["caption_original"].dropna().astype(str).replace("", pd.NA).dropna()
    header = f"Case {case_id}."
    if len(caption):
        header += f" Original image: {caption.iloc[0]}."

    method_lines = []
    for method in ["gradcam", "lime", "integrated_gradients", "saliency", "anchor"]:
        rows = group[group["method"] == method]
        if rows.empty:
            continue
        desc = rows["descripcion"].iloc[0]
        method_lines.append(f"- {method}: {desc}")
    return header + "\n" + "\n".join(method_lines)


df_case_summaries = (
    df_descriptions.groupby("case_id", sort=True)
    .apply(build_case_summary, include_groups=False)
    .reset_index(name="resumen_xai")
)

display(df_case_summaries.head())

   case_id                                        resumen_xai
0  image01  Case image01. Original image: A bird of prey, ...
1  image02  Case image02. Original image: A close-up profi...
2  image03  Case image03. Original image: A snake with a d...
3  image04  Case image04. Original image: A small spider w...
4  image05  Case image05. Original image: A vibrant blue b...

## 7. Guardar resultados

In [43]:
csv_path = OUT_DIR / "descripciones_por_imagen_xai.csv"
xlsx_path = OUT_DIR / "descripciones_por_imagen_xai.xlsx"
summary_csv_path = OUT_DIR / "resumenes_por_caso_xai.csv"


df_descriptions.to_csv(csv_path, index=False, encoding="utf-8")
df_case_summaries.to_csv(summary_csv_path, index=False, encoding="utf-8")

try:
    df_descriptions.to_excel(xlsx_path, index=False)
except Exception as exc:
    print("No se pudo guardar XLSX. Instala openpyxl si lo necesitas: %pip install openpyxl")
    print(type(exc).__name__, str(exc)[:200])



print("Archivos generados:")
print(csv_path)
print(summary_csv_path)

if xlsx_path.exists():
    print(xlsx_path)

Archivos generados:
/Users/haojie/PycharmProjects/TFM-Personalized-XAI/generacion_descripcion_XAI/resultados_descripciones_xai/descripciones_por_imagen_xai.csv
/Users/haojie/PycharmProjects/TFM-Personalized-XAI/generacion_descripcion_XAI/resultados_descripciones_xai/resumenes_por_caso_xai.csv
/Users/haojie/PycharmProjects/TFM-Personalized-XAI/generacion_descripcion_XAI/resultados_descripciones_xai/descripciones_por_imagen_xai.xlsx

## 8. Vista rápida de un caso

In [44]:
CASE_ID = df_case_summaries["case_id"].iloc[0]

display(Markdown(df_case_summaries.loc[df_case_summaries["case_id"] == CASE_ID, "resumen_xai"].iloc[0]))
display(df_descriptions[df_descriptions["case_id"] == CASE_ID][["method", "image_path", "descripcion"]])

Case image01. Original image: A bird of prey, with dark brown and white plumage, soars gracefully through a clear blue sky, its wings fully extended and tail feathers fanned out as it glides forward..
- gradcam: The base image shows: A bird of prey, with dark brown and white plumage, soars gracefully through a clear blue sky, its wings fully extended and tail feathers fanned out as it glides forward.. Method gradcam: Grad-CAM highlights the warm regions of the map as the most relevant areas, indicating the parts of the image that most influenced the predicted class. The generated visualization can be visually described as: This XAI visualization compares an original image of a bird in flight with a heatmap and an overlay, highlighting a warm, bright region around the bird's body and wings, suggesting that the model's attention is focused on these areas, likely indicating the bird's identification as a kite with a logit score of 6.43..
- lime: The base image shows: A bird of prey, with dark brown and white plumage, soars gracefully through a clear blue sky, its wings fully extended and tail feathers fanned out as it glides forward.. Method lime: LIME divides the image into superpixels and marks the regions that most support the model prediction. The generated visualization can be visually described as: This XAI visualization compares an original image of a bird in flight with a superpixel mask and a LIME kite explanation, highlighting the bird's silhouette and key features in warm, bright, and marked regions, suggesting the model's focus on the bird's shape and edges for accurate detection..
- integrated_gradients: The base image shows: A bird of prey, with dark brown and white plumage, soars gracefully through a clear blue sky, its wings fully extended and tail feathers fanned out as it glides forward.. Method integrated_gradients: Integrated Gradients assigns importance to pixels by comparing the image with a baseline reference; the most intense regions concentrate the strongest contribution to the prediction. The generated visualization can be visually described as: This XAI visualization compares an original image of a bird in flight with its corresponding IG |abs| (gris) grayscale representation, IG heatmap, and an overlay with a kite (0.28) score, highlighting the bird's wings and body as the most influential features for model predictions, suggesting these areas are critical for accurate classification..
- saliency: The base image shows: A bird of prey, with dark brown and white plumage, soars gracefully through a clear blue sky, its wings fully extended and tail feathers fanned out as it glides forward.. Method saliency: Saliency Maps highlight the pixels where small changes would most affect the model output; brighter areas indicate greater sensitivity. The generated visualization can be visually described as: This XAI visualization compares an original image of a bird in flight with a saliency map highlighting areas of high importance, and an overlay indicating the presence of a kite with a logit score of 6.43, suggesting the model's focus on the bird's wings and body as key features for identifying the kite..
- anchor: The base image shows: A bird of prey, with dark brown and white plumage, soars gracefully through a clear blue sky, its wings fully extended and tail feathers fanned out as it glides forward.. Method anchor: Anchor Image identifies a set of superpixels that act as a sufficient rule for preserving the model prediction. The generated visualization can be visually described as: This XAI visualization compares an original image of a bird in flight with its masked anchor representation, segmented superpixels, and an overlay indicating a kite detection with high precision but zero coverage, highlighting the model's focus on specific regions while missing the broader context.. Anchor metadata: predicted class 'kite', probability 0.276, precision 1.000, coverage 0.001, anchor superpixels [2, 6, 1, 4, 12, 9, 11, 13, 7, 10].

,method,image_path,descripcion
0,anchor,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A bird of prey, with dar..."
1,gradcam,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A bird of prey, with dar..."
2,integrated_gradients,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A bird of prey, with dar..."
3,lime,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A bird of prey, with dar..."
4,original,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A bird of prey, with dar..."
5,saliency,/Users/haojie/PycharmProjects/TFM-Personalized...,"The base image shows: A bird of prey, with dar..."